### ISSUE TITLE
Refactor to React stateless functional components

### ISSUE THREAD

**Issue by karlhorky** [karlhorky/react-malarkey#1]
https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#stateless-functional-components

**Comment by okonet** [comment]
I don't think this is possible to do keeping in mind you're using lifecycle methods. These are only available for classes extended from `React.Component` AFAIK

**Comment by karlhorky** [comment]
Ah okay, and I guess there's no way to get around that, since I want to call malarkey when the component is ready, correct?

I guess I'll close this then.

**Comment by okonet** [comment]
No. And it's okay.
